function(require_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(NOT match)
    message(FATAL_ERROR "Missing ${description}")
  endif()
endfunction()

function(reject_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(match)
    message(FATAL_ERROR "Unexpected ${description}")
  endif()
endfunction()

file(READ "${DEVICE_CONTEXT_HEADER}" header)
file(READ "${DEVICE_CONTEXT_SOURCE}" source)

require_match("${header}" "~DeviceContext\\(\\) noexcept" "non-throwing DeviceContext destructor")
require_match("${header}" "class Resources;" "private resource owner declaration")
require_match("${header}" "std::unique_ptr<Resources> resources_;" "private resource ownership")
require_match("${source}" "#include <raft/core/device_resources\\.hpp>" "explicit RAFT device_resources header")
require_match("${source}" "#include <raft/core/resource/device_memory_resource\\.hpp>" "explicit RAFT device memory resource header")
require_match("${source}" "class DeviceGuard" "device affinity guard")
require_match("${source}" "cudaGetDevice" "caller device capture")
require_match("${source}" "cudaSetDevice" "device selection and restoration")
require_match("${source}" "void restore\\(\\)" "explicit device restoration")
require_match("${source}" "device_guard\\.restore\\(\\);" "checked per-operation restoration")
require_match("${source}" "resources_\\.reset\\(\\);" "resource destruction under the affinity guard")
require_match("${source}" "DeviceGuard device_guard\\{device_id_\\};" "per-operation device selection")
require_match("${source}" "class DeviceAllocation" "RMM allocation scope owner")
require_match("${source}" "cudaStreamSynchronize\\(stream_\\)" "exception-path synchronization")
require_match("${source}" "#include <rmm/aligned\\.hpp>" "RMM allocation alignment header")
require_match("${source}" "allocate\\(stream_ref_, bytes_, rmm::CUDA_ALLOCATION_ALIGNMENT\\)" "explicit RMM allocation alignment")
require_match("${source}" "deallocate\\(stream_ref_, values, bytes_, rmm::CUDA_ALLOCATION_ALIGNMENT\\)" "matching explicit RMM deallocation alignment")
require_match("${source}" "#include <rmm/mr/cuda_memory_resource\\.hpp>" "RMM 26.06 CUDA memory resource header")
require_match("${source}" "#include <rmm/mr/pool_memory_resource\\.hpp>" "RMM 26.06 pool memory resource header")
require_match("${source}" "cuda_resource_\\(\\), pool_\\(cuda_resource_, initial_pool_bytes\\), resources_\\(\\)" "resource construction order preserving upstream and pool lifetimes")
require_match("${source}" "raft::resource::set_workspace_resource\\(resources_, raft::mr::device_resource\\{pool_\\}\\)" "RAFT workspace bound to owned RMM pool")
require_match("${source}" "raft::resource::set_large_workspace_resource\\(resources_, raft::mr::device_resource\\{pool_\\}\\)" "RAFT large workspace bound to owned RMM pool")
require_match("${source}" "rmm::mr::cuda_memory_resource cuda_resource_;[ \n]+rmm::mr::pool_memory_resource pool_;[ \n]+raft::device_resources resources_;" "member declaration order destroys RAFT resources before pool before CUDA upstream")
reject_match("${source}" "rmm/mr/device/" "pre-26.06 RMM device memory resource include path")
