function(require_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(NOT match)
    message(FATAL_ERROR "Missing ${description}")
  endif()
endfunction()

function(reject_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(match)
    message(FATAL_ERROR "Unexpected ${description}")
  endif()
endfunction()

file(READ "${DEVICE_CONTEXT_HEADER}" header)
file(READ "${DEVICE_CONTEXT_SOURCE}" source)

require_match("${header}" "~DeviceContext\\(\\) noexcept" "non-throwing DeviceContext destructor")
require_match("${header}" "class Resources;" "private resource owner declaration")
require_match("${header}" "std::unique_ptr<Resources> resources_;" "private resource ownership")
require_match("${source}" "#include <raft/core/device_resources\\.hpp>" "explicit RAFT device_resources header")
require_match("${source}" "class DeviceGuard" "device affinity guard")
require_match("${source}" "cudaGetDevice" "caller device capture")
require_match("${source}" "cudaSetDevice" "device selection and restoration")
require_match("${source}" "void restore\\(\\)" "explicit device restoration")
require_match("${source}" "device_guard\\.restore\\(\\);" "checked per-operation restoration")
require_match("${source}" "resources_\\.reset\\(\\);" "resource destruction under the affinity guard")
require_match("${source}" "DeviceGuard device_guard\\{device_id_\\};" "per-operation device selection")
require_match("${source}" "class DeviceAllocation" "RMM allocation scope owner")
require_match("${source}" "cudaStreamSynchronize\\(stream_\\)" "exception-path synchronization")
require_match("${source}" "#include <rmm/mr/cuda_memory_resource\\.hpp>" "RMM 26.06 CUDA memory resource header")
require_match("${source}" "#include <rmm/mr/pool_memory_resource\\.hpp>" "RMM 26.06 pool memory resource header")
reject_match("${source}" "rmm/mr/device/" "pre-26.06 RMM device memory resource include path")
