function(require_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(NOT match)
    message(FATAL_ERROR "Missing ${description}")
  endif()
endfunction()

function(reject_match content expression description)
  string(REGEX MATCH "${expression}" match "${content}")
  if(match)
    message(FATAL_ERROR "Unexpected ${description}")
  endif()
endfunction()

file(READ "${DEVICE_CONTEXT_HEADER}" header)
file(READ "${DEVICE_CONTEXT_SOURCE}" source)
file(READ "${WORKSPACE_ARENA_HEADER}" arena_header)
file(READ "${WORKSPACE_ARENA_SOURCE}" arena_source)

require_match("${header}" "~DeviceContext\\(\\) noexcept" "non-throwing DeviceContext destructor")
require_match("${header}" "class Resources;" "private resource owner declaration")
require_match("${header}" "std::unique_ptr<Resources> resources_;" "private resource ownership")
require_match("${source}" "#include <raft/core/device_resources\\.hpp>" "explicit RAFT device_resources header")
require_match("${source}" "#include <raft/core/resource/device_memory_resource\\.hpp>" "explicit RAFT device memory resource header")
require_match("${source}" "#include \"\\.\\./execution/execution_context\\.hpp\"" "execution context include")
require_match("${source}" "#include \"\\.\\./execution/workspace_arena\\.hpp\"" "workspace arena include")
require_match("${source}" "class DeviceGuard" "device affinity guard")
require_match("${source}" "cudaGetDevice" "caller device capture")
require_match("${source}" "cudaSetDevice" "device selection and restoration")
require_match("${source}" "void restore\\(\\)" "explicit device restoration")
require_match("${source}" "device_guard\\.restore\\(\\);" "checked per-operation restoration")
require_match("${source}" "resources_\\.reset\\(\\);" "resource destruction under the affinity guard")
require_match("${source}" "DeviceGuard device_guard\\{device_id_\\};" "per-operation device selection")
require_match("${source}" "#include <rmm/mr/cuda_memory_resource\\.hpp>" "RMM 26.06 CUDA memory resource header")
require_match("${source}" "#include <rmm/mr/pool_memory_resource\\.hpp>" "RMM 26.06 pool memory resource header")
require_match("${source}" "cuda_resource_\\(\\), pool_\\(cuda_resource_, initial_pool_bytes\\), workspace_arena_\\(\\), resources_\\(\\)" "resource construction order preserving upstream, pool, arena, and RAFT lifetimes")
require_match("${source}" "raft::resource::set_workspace_resource\\(resources_, raft::mr::device_resource\\{pool_\\}\\)" "RAFT workspace bound to owned RMM pool")
require_match("${source}" "raft::resource::set_large_workspace_resource\\(resources_, raft::mr::device_resource\\{pool_\\}\\)" "RAFT large workspace bound to owned RMM pool")
require_match("${source}" "workspace_arena_\\.emplace\\([ \n]+rmm::device_async_resource_ref\\{pool_\\}, cuda::stream_ref\\{stream\\}, stream, kWorkspaceBytes\\)" "1 MiB workspace arena owned by Resources")
require_match("${source}" "void probe_workspace\\(\\)" "private workspace allocation/reset probe")
require_match("${source}" "resources_->probe_workspace\\(\\);" "smoke path invokes workspace probe")
require_match("${source}" "workspace\\.allocate\\(count \\* sizeof\\(uint32_t\\), alignof\\(uint32_t\\)\\)" "smoke device buffer allocated from workspace arena")
require_match("${source}" "rmm::mr::cuda_memory_resource cuda_resource_;[ \n]+rmm::mr::pool_memory_resource pool_;[ \n]+std::optional<WorkspaceArena> workspace_arena_;[ \n]+raft::device_resources resources_;" "member declaration order destroys RAFT resources before workspace arena before pool before CUDA upstream")
reject_match("${source}" "class DeviceAllocation" "per-smoke RMM allocation scope owner")
reject_match("${source}" "rmm/mr/device/" "pre-26.06 RMM device memory resource include path")

require_match("${arena_header}" "class WorkspaceArena" "workspace arena owner")
require_match("${arena_source}" "#include <rmm/aligned\\.hpp>" "workspace arena RMM allocation alignment header")
require_match("${arena_source}" "allocate\\(stream_ref_, bytes_, rmm::CUDA_ALLOCATION_ALIGNMENT\\)" "explicit arena RMM allocation alignment")
require_match("${arena_source}" "deallocate\\(stream_ref_, base, bytes_, rmm::CUDA_ALLOCATION_ALIGNMENT\\)" "matching explicit arena RMM deallocation alignment")
require_match("${arena_source}" "cudaStreamSynchronize\\(stream_\\)" "arena destruction synchronization")
