option(BRT_ENABLE_CUDA "Build the RAFT/RMM CUDA backend" OFF)
option(BRT_BUILD_TESTS "Build BRT tests" ON)

if(NOT DEFINED BRT_NATIVE_LIBRARY_TYPE)
  if(BRT_ENABLE_CUDA)
    set(BRT_NATIVE_LIBRARY_TYPE "SHARED" CACHE STRING
      "Native BRT library type (STATIC or SHARED)")
  else()
    set(BRT_NATIVE_LIBRARY_TYPE "STATIC" CACHE STRING
      "Native BRT library type (STATIC or SHARED)")
  endif()
endif()
set_property(CACHE BRT_NATIVE_LIBRARY_TYPE PROPERTY STRINGS STATIC SHARED)
string(TOUPPER "${BRT_NATIVE_LIBRARY_TYPE}" BRT_NATIVE_LIBRARY_TYPE)
if(NOT BRT_NATIVE_LIBRARY_TYPE STREQUAL "STATIC" AND
   NOT BRT_NATIVE_LIBRARY_TYPE STREQUAL "SHARED")
  message(FATAL_ERROR
    "BRT_NATIVE_LIBRARY_TYPE must be STATIC or SHARED, got: "
    "${BRT_NATIVE_LIBRARY_TYPE}")
endif()

if(BRT_ENABLE_CUDA)
  enable_language(CUDA)
  set(CMAKE_CUDA_ARCHITECTURES 120a CACHE STRING "CUDA architectures" FORCE)
endif()
