option(RAFTINFER_ENABLE_CUDA "Build the RAFT/RMM CUDA backend" OFF)
option(RAFTINFER_BUILD_TESTS "Build RAFTInfer tests" ON)

if(NOT DEFINED RAFTINFER_NATIVE_LIBRARY_TYPE)
  if(RAFTINFER_ENABLE_CUDA)
    set(RAFTINFER_NATIVE_LIBRARY_TYPE "SHARED" CACHE STRING
      "Native RAFTInfer library type (STATIC or SHARED)")
  else()
    set(RAFTINFER_NATIVE_LIBRARY_TYPE "STATIC" CACHE STRING
      "Native RAFTInfer library type (STATIC or SHARED)")
  endif()
endif()
set_property(CACHE RAFTINFER_NATIVE_LIBRARY_TYPE PROPERTY STRINGS STATIC SHARED)
string(TOUPPER "${RAFTINFER_NATIVE_LIBRARY_TYPE}" RAFTINFER_NATIVE_LIBRARY_TYPE)
if(NOT RAFTINFER_NATIVE_LIBRARY_TYPE STREQUAL "STATIC" AND
   NOT RAFTINFER_NATIVE_LIBRARY_TYPE STREQUAL "SHARED")
  message(FATAL_ERROR
    "RAFTINFER_NATIVE_LIBRARY_TYPE must be STATIC or SHARED, got: "
    "${RAFTINFER_NATIVE_LIBRARY_TYPE}")
endif()

if(RAFTINFER_ENABLE_CUDA)
  enable_language(CUDA)
  set(CMAKE_CUDA_ARCHITECTURES 120a CACHE STRING "CUDA architectures" FORCE)
endif()
